name = "dt-trading"
pages_build_output_dir = "dist"
compatibility_date = "2024-02-14"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "dt-trading-db"
database_id = "8deb85d2-3605-4edb-9144-0e07371ce623"

# R2 Storage
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dt-trading-assets"
